name: masamune_core
description: >-
  Library that provides the core part of the Masamune framework.
  It provides Path map, data management, task management and utility.
version: 0.2.11+7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_core

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Web
  http: ^0.12.1
  # Data
  csv: ^4.0.3
  shared_preferences: 0.5.6+3
  # Utility
  intl: ^0.16.1
  uuid: ^2.0.4
  crypto: ^2.1.3
  sprintf: ^4.0.0
  stack_trace: ^1.9.3
  url_launcher: ^5.4.7
  path_provider: ^1.6.11
  # Masamune
  masamune_localize: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0

# dependency_overrides:
#   masamune_localize:
#     path: ../masamune_localize/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
